study_name:
  flow_learn

n_trials: 100

params:
  stage.train.learn.learning_rate:
    suggest: suggest_float
    settings:
      low: 1e-04
      high: 5e-03
      log: true

  stage.train.learn.scheduler.warmup_steps:
    suggest: suggest_int
    settings:
      low: 0
      high: 20

  stage.train.learn.opt_settings.weight_decay:
    suggest: suggest_float
    settings:
      low: 1e-06
      high: 1e-03
      log: true
