checkpoint_every:
  50
cuda: true
generate:
  batch_size: 16
  bias_dim: 0
  bias_value: 0.
path: {}
    # exp_par_dir:
    # metadata_dir:
    # data_dir:
plot:
    training: true
    interactive: false
    refresh: 10
    indices_to_reconstruct: [0, 1, 2, 3, 4]

validate: 10