study_name:
  latent_encoder

n_trials: 300

params:

  autoencoder.model.latent_encoder.mlp_dims:
    suggest: suggest_list
    settings:
      min_length: 1
      max_length: 3
      suggest: suggest_categorical
      settings:
        choices: [256, 512, 1024]
